services:
  web:
    container_name: adtestpro
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=development
    networks:
      - adtestpro-network

networks:
  adtestpro-network:
    name: adtestpro-network
