"""initial migration

Revision ID: 165b91bc2b81
Revises: 
Create Date: 2024-11-25 18:55:25.947946

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "165b91bc2b81"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "target_audiences",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("age_range", sa.String(), nullable=True),
        sa.Column("gender", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("interests", sa.String(), nullable=True),
        sa.Column("pain_points", sa.String(), nullable=True),
        sa.Column("generated_personas", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_target_audiences_id"),
        "target_audiences",
        ["id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "impersonation_results",
        "target_audiences",
        ["target_audience_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "impersonation_results", type_="foreignkey")
    op.drop_index(
        op.f("ix_target_audiences_id"), table_name="target_audiences"
    )
    op.drop_table("target_audiences")
    # ### end Alembic commands ###
