"""Initial migration

Revision ID: 9cfd33236889
Revises: 
Create Date: 2024-11-25 15:03:10.844883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cfd33236889'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('image_data', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_images_id'), 'ad_images', ['id'], unique=False)
    op.create_table('target_audiences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('age_range', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('interests', sa.JSON(), nullable=True),
    sa.Column('pain_points', sa.JSON(), nullable=True),
    sa.Column('generated_personas', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_target_audiences_id'), 'target_audiences', ['id'], unique=False)
    op.create_table('ad_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ad_image_id', sa.Integer(), nullable=True),
    sa.Column('engagement_elements', sa.JSON(), nullable=True),
    sa.Column('text_tone', sa.JSON(), nullable=True),
    sa.Column('visual_elements', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ad_image_id'], ['ad_images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_analysis_id'), 'ad_analysis', ['id'], unique=False)
    op.create_table('impersonation_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ad_image_id', sa.Integer(), nullable=True),
    sa.Column('target_audience_id', sa.Integer(), nullable=True),
    sa.Column('selected_questions', sa.JSON(), nullable=True),
    sa.Column('responses', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ad_image_id'], ['ad_images.id'], ),
    sa.ForeignKeyConstraint(['target_audience_id'], ['target_audiences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impersonation_results_id'), 'impersonation_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_impersonation_results_id'), table_name='impersonation_results')
    op.drop_table('impersonation_results')
    op.drop_index(op.f('ix_ad_analysis_id'), table_name='ad_analysis')
    op.drop_table('ad_analysis')
    op.drop_index(op.f('ix_target_audiences_id'), table_name='target_audiences')
    op.drop_table('target_audiences')
    op.drop_index(op.f('ix_ad_images_id'), table_name='ad_images')
    op.drop_table('ad_images')
    # ### end Alembic commands ###
